import { z } from 'zod';
import { supabase } from '@/integrations/supabase/client';

// ─── Schemas ──────────────────────────────────────────────────────────
export const budgetNameSchema = z
  .string()
  .trim()
  .min(1, 'El nombre no puede estar vacío')
  .max(120, 'El nombre es demasiado largo (máx. 120)');

// Fields we never copy when duplicating a budget header
// (auto-generated by DB, fiscal/accounting state, or "primary" flag).
const HEADER_EXCLUDED_FIELDS = new Set<string>([
  'id',
  'created_at',
  'updated_at',
  'created_by',
  'is_primary_for_booking', // copy never inherits primary flag
  'accountant_verified_at',
  'accountant_verified_by',
  'estimated_version_id',
  'final_version_id',
  'settlement_status',
  'status_negociacion',
]);

const ITEM_EXCLUDED_FIELDS = new Set<string>([
  'id',
  'budget_id',
  'created_at',
  'updated_at',
  // Reset reconciliation/invoicing state on a fresh copy
  'is_reconciled',
  'reconciled_at',
  'reconciled_by',
  'billing_status',
  'invoice_group_parent_id',
  'invoice_link',
  'fecha_emision',
  'provider_invoice_received_at',
  'provider_invoice_requested_at',
  'provider_invoice_status',
  'supplier_invoice_number',
  'supplier_invoice_total',
]);

function pickAllowed<T extends Record<string, any>>(
  row: T,
  excluded: Set<string>
): Partial<T> {
  const out: Record<string, any> = {};
  for (const [k, v] of Object.entries(row)) {
    if (excluded.has(k)) continue;
    out[k] = v;
  }
  return out as Partial<T>;
}

// ─── Rename ───────────────────────────────────────────────────────────
export async function renameBudget(budgetId: string, newName: string) {
  const parsed = budgetNameSchema.safeParse(newName);
  if (!parsed.success) {
    throw new Error(parsed.error.issues[0]?.message || 'Nombre inválido');
  }

  const { data, error } = await supabase
    .from('budgets')
    .update({ name: parsed.data })
    .eq('id', budgetId)
    .select('id, name')
    .single();

  if (error) throw error;
  return data;
}

// ─── Deletion impact / Delete ─────────────────────────────────────────
const uuidSchema = z.string().uuid('Identificador inválido');

export interface BudgetDeletionImpact {
  itemCount: number;
  totalCapital: number;
  totalPaid: number;
  paidItemCount: number;
  reconciledItemCount: number;
  hasPaidItems: boolean;
  hasReconciledItems: boolean;
  isPrimary: boolean;
  budgetName: string;
}

const PAID_BILLING_STATUSES = new Set([
  'paid',
  'pagado',
  'cobrado',
  'cobrado_completo',
  'partially_paid',
  'cobrado_parcial',
]);

export async function getBudgetDeletionImpact(
  budgetId: string
): Promise<BudgetDeletionImpact> {
  const id = uuidSchema.parse(budgetId);

  const { data: header, error: hErr } = await supabase
    .from('budgets')
    .select('id, name, is_primary_for_booking')
    .eq('id', id)
    .single();
  if (hErr || !header) throw new Error('No se pudo leer el presupuesto');

  const { data: items, error: iErr } = await supabase
    .from('budget_items')
    .select('unit_price, quantity, billing_status, is_reconciled')
    .eq('budget_id', id);
  if (iErr) throw iErr;

  let totalCapital = 0;
  let totalPaid = 0;
  let paidItemCount = 0;
  let reconciledItemCount = 0;

  for (const it of items || []) {
    const subtotal = (Number(it.unit_price) || 0) * (Number(it.quantity) || 0);
    totalCapital += subtotal;
    const status = (it.billing_status || '').toLowerCase();
    if (PAID_BILLING_STATUSES.has(status)) {
      totalPaid += subtotal;
      paidItemCount += 1;
    }
    if (it.is_reconciled) reconciledItemCount += 1;
  }

  return {
    itemCount: items?.length || 0,
    totalCapital,
    totalPaid,
    paidItemCount,
    reconciledItemCount,
    hasPaidItems: paidItemCount > 0,
    hasReconciledItems: reconciledItemCount > 0,
    isPrimary: !!header.is_primary_for_booking,
    budgetName: header.name || '',
  };
}

export async function deleteBudget(budgetId: string): Promise<void> {
  const id = uuidSchema.parse(budgetId);

  // Defense-in-depth: re-check impact server-side before deletion
  const impact = await getBudgetDeletionImpact(id);
  if (impact.hasPaidItems) {
    throw new Error(
      'No se puede eliminar: el presupuesto tiene partidas cobradas/pagadas. Desvincúlalas primero desde Finanzas.'
    );
  }

  const { error: itemsErr } = await supabase
    .from('budget_items')
    .delete()
    .eq('budget_id', id);
  if (itemsErr) throw itemsErr;

  const { error: budgetErr } = await supabase
    .from('budgets')
    .delete()
    .eq('id', id);
  if (budgetErr) throw budgetErr;
}

// ─── Primary flag management ──────────────────────────────────────────
export async function setPrimaryBudget(bookingId: string, newPrimaryId: string) {
  if (!bookingId || !newPrimaryId) throw new Error('Faltan parámetros');

  // 1. Clear any existing primary on this booking
  const { error: clearErr } = await supabase
    .from('budgets')
    .update({ is_primary_for_booking: false })
    .eq('booking_offer_id', bookingId)
    .eq('is_primary_for_booking', true);
  if (clearErr) throw clearErr;

  // 2. Mark new primary
  const { error: setErr } = await supabase
    .from('budgets')
    .update({ is_primary_for_booking: true })
    .eq('id', newPrimaryId);
  if (setErr) throw setErr;
}

export async function unlinkBudgetFromBooking(budgetId: string) {
  if (!budgetId) throw new Error('Falta el id del presupuesto');

  // Block if it's the only/primary budget — caller should promote another first
  const { data: b, error: rErr } = await supabase
    .from('budgets')
    .select('booking_offer_id, is_primary_for_booking')
    .eq('id', budgetId)
    .single();
  if (rErr || !b) throw new Error('No se pudo leer el presupuesto');

  if (b.is_primary_for_booking) {
    const { count } = await supabase
      .from('budgets')
      .select('id', { count: 'exact', head: true })
      .eq('booking_offer_id', b.booking_offer_id!);
    if ((count ?? 0) > 1) {
      throw new Error('Este es el presupuesto principal. Marca otro como principal antes de desvincular.');
    }
  }

  const { error } = await supabase
    .from('budgets')
    .update({ booking_offer_id: null, is_primary_for_booking: false })
    .eq('id', budgetId);
  if (error) throw error;
}

// ─── Duplicate ────────────────────────────────────────────────────────
const PAGE_SIZE = 500;

export async function duplicateBudget(sourceBudgetId: string, userId: string) {
  if (!sourceBudgetId) throw new Error('Falta el id del presupuesto origen');
  if (!userId) throw new Error('Usuario no autenticado');

  // 1. Read source header
  const { data: source, error: srcErr } = await supabase
    .from('budgets')
    .select('*')
    .eq('id', sourceBudgetId)
    .single();

  if (srcErr || !source) {
    throw new Error('No se pudo leer el presupuesto origen');
  }

  // 2. Build new header (strip excluded + auto fields, force new name + creator)
  const headerInsert: Record<string, any> = {
    ...pickAllowed(source, HEADER_EXCLUDED_FIELDS),
    name: `${source.name} (copia)`.slice(0, 120),
    created_by: userId,
    is_primary_for_booking: false,
  };

  const { data: newBudget, error: insErr } = await supabase
    .from('budgets')
    .insert(headerInsert as any)
    .select('*')
    .single();

  if (insErr || !newBudget) {
    throw new Error(insErr?.message || 'No se pudo duplicar el presupuesto');
  }

  // 3. Copy items in pages
  try {
    let from = 0;
    while (true) {
      const { data: items, error: itemsErr } = await supabase
        .from('budget_items')
        .select('*')
        .eq('budget_id', sourceBudgetId)
        .range(from, from + PAGE_SIZE - 1);

      if (itemsErr) throw itemsErr;
      if (!items || items.length === 0) break;

      const toInsert = items.map((it) => ({
        ...pickAllowed(it, ITEM_EXCLUDED_FIELDS),
        budget_id: newBudget.id,
      }));

      if (toInsert.length > 0) {
        const { error: insItemsErr } = await supabase
          .from('budget_items')
          .insert(toInsert as any);
        if (insItemsErr) throw insItemsErr;
      }

      if (items.length < PAGE_SIZE) break;
      from += PAGE_SIZE;
    }
  } catch (e) {
    // Rollback: delete the new header so we don't leave it half-populated
    await supabase.from('budgets').delete().eq('id', newBudget.id);
    throw e instanceof Error
      ? e
      : new Error('Error al duplicar las partidas del presupuesto');
  }

  return newBudget;
}
