// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hptjzbaiclmgbvxlmllo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwdGp6YmFpY2xtZ2J2eGxtbGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzQ1NjksImV4cCI6MjA2OTc1MDU2OX0.kUMKL4MrXFa2qSMjAQtsQP_EZalaTUAdE7WP6j33bb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});