import { Mic, Map, Wallet, Calculator, Disc3, Film, Music } from 'lucide-react';

export interface AutomationDefinition {
  key: string;
  title: string;
  description: string;
  category: string;
  module: string;
  industryTip?: string;
  defaultTriggerDays: number | null; // null = immediate
  triggerDaysRange?: [number, number];
  defaultNotifyRole: string;
  defaultChannel: 'in_app' | 'email' | 'whatsapp';
  ctaLabel: string;
  recommended: boolean;
}

export const AUTOMATION_MODULES = [
  { id: 'booking', label: 'Booking', icon: Mic },
  { id: 'roadmaps', label: 'Hojas de Ruta', icon: Map },
  { id: 'finanzas', label: 'Finanzas', icon: Wallet },
  { id: 'presupuestos', label: 'Presupuestos', icon: Calculator },
  { id: 'discografica', label: 'Discográfica', icon: Disc3 },
  { id: 'sincronizaciones', label: 'Sincronizaciones', icon: Film },
  { id: 'artistas', label: 'Artistas', icon: Music },
] as const;

export const NOTIFY_ROLE_OPTIONS = [
  { value: 'equipo_booking', label: 'Equipo Booking' },
  { value: 'tour_manager', label: 'Tour Manager' },
  { value: 'administracion', label: 'Administración' },
  { value: 'equipo_marketing', label: 'Equipo Marketing' },
  { value: 'artista', label: 'Artista' },
  { value: 'yo', label: 'Yo mismo' },
  { value: 'promotor', label: 'Promotor (externo)' },
  { value: 'sello', label: 'Sello (externo)' },
];

export const CHANNEL_OPTIONS = [
  { value: 'in_app', label: 'In-app' },
  { value: 'email', label: 'Email' },
  { value: 'whatsapp', label: 'WhatsApp' },
] as const;

export const AUTOMATIONS: AutomationDefinition[] = [
  // ── BOOKING: Gestión de Ofertas ──
  {
    key: 'booking_offer_no_response',
    title: 'Oferta sin respuesta',
    description: 'Oferta en fase "Interés" sin actividad durante el periodo configurado.',
    category: 'Gestión de Ofertas',
    module: 'booking',
    industryTip: 'Las ofertas sin respuesta en 72h suelen perderse.',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Enviar recordatorio al promotor',
    recommended: true,
  },
  {
    key: 'booking_negotiation_stalled',
    title: 'Negociación estancada',
    description: 'Oferta en "Negociación" sin cambios durante el periodo configurado.',
    category: 'Gestión de Ofertas',
    module: 'booking',
    defaultTriggerDays: 5,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Registrar seguimiento',
    recommended: true,
  },
  {
    key: 'booking_check_availability',
    title: 'Consultar disponibilidad del equipo',
    description: 'Cuando una oferta pasa a "Negociación", notificar para confirmar disponibilidad.',
    category: 'Gestión de Ofertas',
    module: 'booking',
    industryTip: 'La disponibilidad debe confirmarse antes de cualquier negociación de condiciones.',
    defaultTriggerDays: null,
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Confirmar disponibilidad',
    recommended: true,
  },
  // ── BOOKING: Gestión de Contratos ──
  {
    key: 'booking_confirmed_no_contract',
    title: 'Evento confirmado sin contrato',
    description: 'Booking pasa a fase "Confirmado" sin contrato generado.',
    category: 'Gestión de Contratos',
    module: 'booking',
    industryTip: 'Ningún evento debe confirmarse sin respaldo contractual.',
    defaultTriggerDays: null,
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Generar Contrato',
    recommended: true,
  },
  {
    key: 'booking_contract_not_sent',
    title: 'Contrato sin enviar a firmar',
    description: 'Contrato generado pero no enviado a firmar.',
    category: 'Gestión de Contratos',
    module: 'booking',
    defaultTriggerDays: 1,
    triggerDaysRange: [1, 7],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Enviar a firmar',
    recommended: true,
  },
  {
    key: 'booking_promoter_signature_pending',
    title: 'Firma del promotor pendiente',
    description: 'Contrato enviado pero sin firma del promotor.',
    category: 'Gestión de Contratos',
    module: 'booking',
    industryTip: 'El plazo estándar de firma en España es 7 días hábiles.',
    defaultTriggerDays: 5,
    triggerDaysRange: [1, 15],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Reclamar firma al promotor',
    recommended: true,
  },
  {
    key: 'booking_signed_no_payment',
    title: 'Contrato firmado sin pago inicial',
    description: 'Contrato 100% firmado, sin pago del 50% registrado.',
    category: 'Gestión de Contratos',
    module: 'booking',
    industryTip: 'El 50% inicial debe cobrarse tras la firma del contrato.',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Reclamar pago inicial (50%)',
    recommended: true,
  },
  // ── BOOKING: Producción y Logística ──
  {
    key: 'booking_roadmap_pending',
    title: 'Hoja de Ruta pendiente',
    description: 'Evento confirmado sin Hoja de Ruta asignada.',
    category: 'Producción y Logística',
    module: 'booking',
    defaultTriggerDays: 30,
    triggerDaysRange: [7, 60],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Crear Hoja de Ruta',
    recommended: true,
  },
  {
    key: 'booking_rider_missing',
    title: 'Rider técnico no subido',
    description: 'Evento sin rider en Archivos & Docs.',
    category: 'Producción y Logística',
    module: 'booking',
    industryTip: 'Los festivales requieren el rider con 15-21 días de antelación.',
    defaultTriggerDays: 21,
    triggerDaysRange: [7, 30],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Subir Rider Técnico',
    recommended: true,
  },
  {
    key: 'booking_travel_expenses',
    title: 'Gastos de viaje sin estimar',
    description: 'Evento confirmado sin Travel Expenses registrados.',
    category: 'Producción y Logística',
    module: 'booking',
    defaultTriggerDays: 14,
    triggerDaysRange: [7, 30],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Estimar gastos de viaje',
    recommended: false,
  },
  {
    key: 'booking_press_accreditations',
    title: 'Acreditaciones de prensa',
    description: 'Evento confirmado sin gestión de acreditaciones.',
    category: 'Producción y Logística',
    module: 'booking',
    industryTip: 'Los festivales cierran acreditaciones 2-3 semanas antes.',
    defaultTriggerDays: 21,
    triggerDaysRange: [7, 30],
    defaultNotifyRole: 'equipo_marketing',
    defaultChannel: 'in_app',
    ctaLabel: 'Gestionar acreditaciones',
    recommended: false,
  },
  // ── BOOKING: Comunicación ──
  {
    key: 'booking_announce_pending',
    title: 'Anuncio de concierto pendiente',
    description: 'Evento confirmado sin actividad de marketing registrada.',
    category: 'Comunicación y Promoción',
    module: 'booking',
    defaultTriggerDays: 14,
    triggerDaysRange: [7, 30],
    defaultNotifyRole: 'equipo_marketing',
    defaultChannel: 'in_app',
    ctaLabel: 'Registrar actividad de comunicación',
    recommended: false,
  },
  // ── BOOKING: Facturación ──
  {
    key: 'booking_final_payment',
    title: 'Pago final pendiente',
    description: 'Evento en fase "Facturado" sin cobro del 50% restante.',
    category: 'Facturación y Cierre',
    module: 'booking',
    defaultTriggerDays: 3,
    triggerDaysRange: [0, 7],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Reclamar pago final (50%)',
    recommended: true,
  },
  {
    key: 'booking_invoice_missing',
    title: 'Factura no subida post-evento',
    description: 'Evento pasado sin factura en Drive.',
    category: 'Facturación y Cierre',
    module: 'booking',
    industryTip: 'Las facturas deben emitirse en los 30 días posteriores al evento según normativa española.',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Subir factura',
    recommended: true,
  },
  {
    key: 'booking_economic_close',
    title: 'Cierre económico pendiente',
    description: 'Evento sin cierre económico registrado.',
    category: 'Facturación y Cierre',
    module: 'booking',
    defaultTriggerDays: 7,
    triggerDaysRange: [3, 30],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Completar cierre económico',
    recommended: true,
  },
  // ── HOJAS DE RUTA ──
  {
    key: 'roadmap_draft_pending',
    title: 'Hoja de Ruta en borrador',
    description: 'Hoja de Ruta sin publicar a pocos días del evento.',
    category: 'Hojas de Ruta',
    module: 'roadmaps',
    defaultTriggerDays: 7,
    triggerDaysRange: [3, 14],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Publicar Hoja de Ruta',
    recommended: true,
  },
  {
    key: 'roadmap_hospitality_empty',
    title: 'Hospitalidad no completada',
    description: 'Bloque "Hospitalidad" vacío en la Hoja de Ruta.',
    category: 'Hojas de Ruta',
    module: 'roadmaps',
    defaultTriggerDays: 10,
    triggerDaysRange: [5, 21],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Completar hospitalidad',
    recommended: false,
  },
  // ── FINANZAS ──
  {
    key: 'finance_fee_no_invoice',
    title: 'Fee sin factura asociada',
    description: 'Pago registrado sin factura vinculada.',
    category: 'Finanzas',
    module: 'finanzas',
    defaultTriggerDays: 5,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Vincular factura',
    recommended: true,
  },
  {
    key: 'finance_budget_unapproved',
    title: 'Presupuesto sin aprobar',
    description: 'Presupuesto generado sin aprobación.',
    category: 'Presupuestos',
    module: 'presupuestos',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 7],
    defaultNotifyRole: 'artista',
    defaultChannel: 'in_app',
    ctaLabel: 'Solicitar aprobación',
    recommended: true,
  },
  // ── DISCOGRÁFICA / SINCRONIZACIONES ──
  {
    key: 'sync_no_contract',
    title: 'Sincronización sin contrato',
    description: 'Sincronización en fase avanzada sin contrato.',
    category: 'Sincronizaciones',
    module: 'sincronizaciones',
    defaultTriggerDays: null,
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Generar contrato de sincronización',
    recommended: true,
  },
  {
    key: 'release_master_pending',
    title: 'Masterización pendiente de entrega',
    description: 'Release con fecha pero sin master aprobado.',
    category: 'Discográfica',
    module: 'discografica',
    defaultTriggerDays: 30,
    triggerDaysRange: [14, 60],
    defaultNotifyRole: 'artista',
    defaultChannel: 'in_app',
    ctaLabel: 'Revisar estado del master',
    recommended: true,
  },

  // ── BOOKING: Nuevas del Knowledge Base ──
  {
    key: 'booking_offer_at_risk',
    title: 'Oferta en riesgo',
    description: 'Oferta en fase "Interés" sin movimiento durante 5+ días.',
    category: 'Gestión de Ofertas',
    module: 'booking',
    industryTip: 'Después de 5 días sin respuesta, la probabilidad de cierre cae drásticamente.',
    defaultTriggerDays: 5,
    triggerDaysRange: [3, 14],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Escalar seguimiento',
    recommended: true,
  },
  {
    key: 'booking_formal_offer_no_response',
    title: 'Oferta formal sin respuesta',
    description: 'Oferta formal enviada al promotor sin respuesta en 7+ días.',
    category: 'Gestión de Ofertas',
    module: 'booking',
    industryTip: 'El silencio prolongado tras una oferta formal suele indicar que el promotor está negociando con otros.',
    defaultTriggerDays: 7,
    triggerDaysRange: [3, 14],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Reclamar respuesta al promotor',
    recommended: true,
  },
  {
    key: 'booking_offer_no_rider',
    title: 'Oferta sin rider adjunto',
    description: 'Oferta formal enviada sin rider técnico adjunto.',
    category: 'Gestión de Ofertas',
    module: 'booking',
    industryTip: 'El rider debe acompañar siempre la oferta formal para evitar malentendidos técnicos.',
    defaultTriggerDays: null,
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Adjuntar rider técnico',
    recommended: true,
  },
  {
    key: 'booking_accommodation_pending',
    title: 'Alojamiento sin confirmar',
    description: 'Evento confirmado sin alojamiento gestionado a 14 días del evento.',
    category: 'Producción y Logística',
    module: 'booking',
    industryTip: 'El alojamiento debe confirmarse con al menos 2 semanas de antelación, especialmente en festivales.',
    defaultTriggerDays: 14,
    triggerDaysRange: [7, 30],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Gestionar alojamiento',
    recommended: true,
  },
  {
    key: 'booking_event_reminder',
    title: 'Recordatorio general del evento',
    description: 'Recordatorio al equipo con resumen del evento próximo.',
    category: 'Producción y Logística',
    module: 'booking',
    defaultTriggerDays: 7,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'email',
    ctaLabel: 'Ver detalle del evento',
    recommended: false,
  },
  {
    key: 'booking_real_expenses_missing',
    title: 'Gastos reales no registrados',
    description: 'Evento finalizado sin gastos reales registrados (+3 días post-evento).',
    category: 'Facturación y Cierre',
    module: 'booking',
    industryTip: 'Los gastos deben registrarse inmediatamente tras el evento para un cierre económico preciso.',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 7],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Registrar gastos reales',
    recommended: true,
  },

  // ── HOJAS DE RUTA: Nuevas del Knowledge Base ──
  {
    key: 'roadmap_production_incomplete',
    title: 'Producción técnica sin completar',
    description: 'Bloque de producción técnica incompleto a 21 días del evento.',
    category: 'Hojas de Ruta',
    module: 'roadmaps',
    industryTip: 'La producción técnica debe cerrarse 3 semanas antes para coordinar con el recinto.',
    defaultTriggerDays: 21,
    triggerDaysRange: [7, 30],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Completar producción técnica',
    recommended: true,
  },
  {
    key: 'roadmap_travel_incomplete',
    title: 'Logística de viaje sin completar',
    description: 'Viaje y alojamiento sin completar a 14 días del evento.',
    category: 'Hojas de Ruta',
    module: 'roadmaps',
    industryTip: 'Vuelos y hotel deben reservarse con 2 semanas mínimo de antelación.',
    defaultTriggerDays: 14,
    triggerDaysRange: [7, 21],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Completar logística de viaje',
    recommended: true,
  },
  {
    key: 'roadmap_send_to_promoter',
    title: 'Enviar HdR al promotor',
    description: 'Enviar la Hoja de Ruta definitiva al promotor 3 días antes del evento.',
    category: 'Hojas de Ruta',
    module: 'roadmaps',
    industryTip: 'El promotor necesita la HdR final para coordinar producción local.',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 7],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Enviar HdR al promotor',
    recommended: true,
  },
  {
    key: 'roadmap_event_day_reminder',
    title: 'Recordatorio HdR día del evento',
    description: 'Enviar la Hoja de Ruta al artista y equipo el día del evento.',
    category: 'Hojas de Ruta',
    module: 'roadmaps',
    defaultTriggerDays: 0,
    triggerDaysRange: [0, 1],
    defaultNotifyRole: 'artista',
    defaultChannel: 'whatsapp',
    ctaLabel: 'Enviar HdR al artista',
    recommended: false,
  },

  // ── FINANZAS: Nuevas del Knowledge Base ──
  {
    key: 'finance_sgae_quarterly',
    title: 'Liquidación de SGAE pendiente',
    description: 'Liquidación trimestral de SGAE esperada sin registrar.',
    category: 'Finanzas',
    module: 'finanzas',
    industryTip: 'SGAE liquida trimestralmente; verifica que los importes coinciden con los conciertos declarados.',
    defaultTriggerDays: 90,
    triggerDaysRange: [30, 120],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Registrar liquidación SGAE',
    recommended: true,
  },
  {
    key: 'finance_uncategorized_expenses',
    title: 'Gastos sin categorizar',
    description: 'Gastos de gira registrados sin categoría asignada (revisión mensual).',
    category: 'Finanzas',
    module: 'finanzas',
    defaultTriggerDays: 30,
    triggerDaysRange: [7, 60],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Categorizar gastos pendientes',
    recommended: false,
  },
  {
    key: 'finance_quarterly_tax_prep',
    title: 'Preparación fiscal trimestral',
    description: 'Recordatorio de preparación de documentación fiscal al inicio del trimestre.',
    category: 'Finanzas',
    module: 'finanzas',
    industryTip: 'Prepara la documentación fiscal en los primeros 5 días del trimestre para evitar prisas.',
    defaultTriggerDays: 90,
    triggerDaysRange: [30, 120],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'email',
    ctaLabel: 'Preparar documentación fiscal',
    recommended: true,
  },
  {
    key: 'finance_annual_review',
    title: 'Revisión contable anual',
    description: 'Recordatorio de revisión contable al cierre del ejercicio fiscal.',
    category: 'Finanzas',
    module: 'finanzas',
    defaultTriggerDays: 365,
    triggerDaysRange: [180, 365],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'email',
    ctaLabel: 'Iniciar revisión contable',
    recommended: false,
  },

  // ── PRESUPUESTOS: Nuevas del Knowledge Base ──
  {
    key: 'budget_tour_missing',
    title: 'Gira sin presupuesto',
    description: 'Gira con conciertos confirmados sin presupuesto de gira asociado.',
    category: 'Presupuestos',
    module: 'presupuestos',
    industryTip: 'Todo ciclo de conciertos debe tener un presupuesto de gira para controlar márgenes.',
    defaultTriggerDays: null,
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Crear presupuesto de gira',
    recommended: true,
  },
  {
    key: 'budget_deviation_alert',
    title: 'Desviación presupuestaria >15%',
    description: 'Los gastos reales superan el presupuestado en más de un 15%.',
    category: 'Presupuestos',
    module: 'presupuestos',
    industryTip: 'Desviaciones superiores al 15% requieren revisión inmediata y aprobación.',
    defaultTriggerDays: null,
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Revisar desviación',
    recommended: true,
  },
  {
    key: 'budget_project_start',
    title: 'Presupuesto al iniciar proyecto',
    description: 'Recordatorio de crear presupuesto al iniciar un nuevo proyecto.',
    category: 'Presupuestos',
    module: 'presupuestos',
    defaultTriggerDays: null,
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Crear presupuesto',
    recommended: false,
  },
  {
    key: 'budget_project_close',
    title: 'Comparar presupuesto vs real',
    description: 'Recordatorio de comparar presupuesto vs gastos reales al cerrar proyecto.',
    category: 'Presupuestos',
    module: 'presupuestos',
    defaultTriggerDays: null,
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Comparar presupuesto vs real',
    recommended: false,
  },

  // ── DISCOGRÁFICA: Nuevas del Knowledge Base ──
  {
    key: 'release_distributor_delivery',
    title: 'Entrega al distribuidor pendiente',
    description: 'Entrega de master y assets al distribuidor pendiente (4 semanas antes del lanzamiento).',
    category: 'Discográfica',
    module: 'discografica',
    industryTip: 'Los distribuidores digitales requieren el material con al menos 4 semanas de antelación.',
    defaultTriggerDays: 28,
    triggerDaysRange: [14, 42],
    defaultNotifyRole: 'sello',
    defaultChannel: 'in_app',
    ctaLabel: 'Preparar entrega al distribuidor',
    recommended: true,
  },
  {
    key: 'release_spotify_pitch',
    title: 'Pitch a Spotify editorial',
    description: 'Pitch a Spotify for Artists pendiente (7 semanas antes del lanzamiento).',
    category: 'Discográfica',
    module: 'discografica',
    industryTip: 'Spotify recomienda enviar el pitch al menos 4 semanas antes, pero 7 semanas es ideal.',
    defaultTriggerDays: 49,
    triggerDaysRange: [28, 56],
    defaultNotifyRole: 'equipo_marketing',
    defaultChannel: 'in_app',
    ctaLabel: 'Enviar pitch a Spotify',
    recommended: true,
  },
  {
    key: 'release_artwork_pending',
    title: 'Artwork sin aprobar',
    description: 'Artwork del lanzamiento sin aprobar (6 semanas antes).',
    category: 'Discográfica',
    module: 'discografica',
    industryTip: 'El artwork debe estar aprobado antes de enviar al distribuidor.',
    defaultTriggerDays: 42,
    triggerDaysRange: [21, 56],
    defaultNotifyRole: 'artista',
    defaultChannel: 'in_app',
    ctaLabel: 'Aprobar artwork',
    recommended: true,
  },

  // ── SINCRONIZACIONES: Nuevas del Knowledge Base ──
  {
    key: 'sync_contract_unsigned',
    title: 'Contrato de sync sin firma',
    description: 'Contrato de sincronización generado pero sin firma tras 7+ días.',
    category: 'Sincronizaciones',
    module: 'sincronizaciones',
    defaultTriggerDays: 7,
    triggerDaysRange: [3, 14],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Reclamar firma del contrato',
    recommended: true,
  },
  {
    key: 'sync_request_no_response',
    title: 'Solicitud de sync sin respuesta',
    description: 'Solicitud de sincronización sin respuesta tras 3+ días.',
    category: 'Sincronizaciones',
    module: 'sincronizaciones',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 7],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Seguimiento de solicitud',
    recommended: true,
  },
  {
    key: 'sync_materials_pending',
    title: 'Entrega de materiales pendiente',
    description: 'Materiales de sincronización pendientes de entrega (+2 días tras confirmar).',
    category: 'Sincronizaciones',
    module: 'sincronizaciones',
    defaultTriggerDays: 2,
    triggerDaysRange: [1, 7],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Entregar materiales',
    recommended: false,
  },
  {
    key: 'sync_payment_pending',
    title: 'Pago de sync pendiente',
    description: 'Pago de sincronización no recibido tras 30+ días.',
    category: 'Sincronizaciones',
    module: 'sincronizaciones',
    industryTip: 'Los pagos de sync suelen tener plazo de 30 días desde la firma del contrato.',
    defaultTriggerDays: 30,
    triggerDaysRange: [14, 60],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Reclamar pago',
    recommended: true,
  },
  {
    key: 'sync_check_rights',
    title: 'Consultar disponibilidad de derechos',
    description: 'Brief de sync recibido: consultar disponibilidad de derechos de la canción.',
    category: 'Sincronizaciones',
    module: 'sincronizaciones',
    industryTip: 'Antes de responder a un brief, verifica que los derechos están disponibles para el territorio solicitado.',
    defaultTriggerDays: null,
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Verificar derechos',
    recommended: true,
  },

  // ── ARTISTAS: Nuevas del Knowledge Base ──
  {
    key: 'artist_bio_outdated',
    title: 'Bio desactualizada',
    description: 'Biografía del artista no actualizada en más de 18 meses.',
    category: 'Artistas',
    module: 'artistas',
    industryTip: 'La bio debe actualizarse al menos una vez al año o tras cada lanzamiento importante.',
    defaultTriggerDays: 540,
    triggerDaysRange: [180, 730],
    defaultNotifyRole: 'equipo_marketing',
    defaultChannel: 'in_app',
    ctaLabel: 'Actualizar biografía',
    recommended: true,
  },
  {
    key: 'artist_photos_outdated',
    title: 'Fotos de prensa desactualizadas',
    description: 'Fotos de prensa no actualizadas en más de 18 meses.',
    category: 'Artistas',
    module: 'artistas',
    industryTip: 'Las fotos de prensa deben renovarse al menos cada 18 meses para mantener la imagen fresca.',
    defaultTriggerDays: 540,
    triggerDaysRange: [180, 730],
    defaultNotifyRole: 'equipo_marketing',
    defaultChannel: 'in_app',
    ctaLabel: 'Programar sesión de fotos',
    recommended: true,
  },
  {
    key: 'artist_no_release',
    title: 'Sin lanzamiento reciente',
    description: 'Artista sin lanzamiento en los últimos 12 meses.',
    category: 'Artistas',
    module: 'artistas',
    industryTip: 'Mantener un flujo constante de lanzamientos es clave para el crecimiento en plataformas digitales.',
    defaultTriggerDays: 365,
    triggerDaysRange: [180, 540],
    defaultNotifyRole: 'artista',
    defaultChannel: 'in_app',
    ctaLabel: 'Planificar próximo lanzamiento',
    recommended: true,
  },
  {
    key: 'artist_no_concerts',
    title: 'Sin conciertos próximos',
    description: 'Artista sin conciertos programados en los próximos 60 días.',
    category: 'Artistas',
    module: 'artistas',
    defaultTriggerDays: 60,
    triggerDaysRange: [30, 90],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Buscar oportunidades de booking',
    recommended: false,
  },
  {
    key: 'artist_contract_expiry',
    title: 'Contrato de management por vencer',
    description: 'Contrato de management del artista próximo a vencer (90 días antes).',
    category: 'Artistas',
    module: 'artistas',
    industryTip: 'Inicia la renegociación del contrato con al menos 3 meses de antelación.',
    defaultTriggerDays: 90,
    triggerDaysRange: [30, 180],
    defaultNotifyRole: 'yo',
    defaultChannel: 'email',
    ctaLabel: 'Iniciar renovación de contrato',
    recommended: true,
  },
  {
    key: 'artist_contract_anniversary',
    title: 'Aniversario de contrato',
    description: 'Aniversario del contrato de management: revisión de condiciones.',
    category: 'Artistas',
    module: 'artistas',
    defaultTriggerDays: 365,
    triggerDaysRange: [180, 365],
    defaultNotifyRole: 'yo',
    defaultChannel: 'in_app',
    ctaLabel: 'Revisar condiciones del contrato',
    recommended: false,
  },
  {
    key: 'artist_quarterly_tax',
    title: 'Declaración trimestral de autónomos',
    description: 'Recordatorio de declaración trimestral de autónomos del artista.',
    category: 'Artistas',
    module: 'artistas',
    industryTip: 'El plazo de presentación del modelo 130/303 es los primeros 20 días del trimestre siguiente.',
    defaultTriggerDays: 90,
    triggerDaysRange: [30, 120],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'email',
    ctaLabel: 'Preparar declaración trimestral',
    recommended: true,
  },
];
